apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-lab-quota
  namespace: gpu-lab
spec:
  hard:
    pods: "3"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    requests.storage: "30Gi"
    persistentvolumeclaims: "3"
