# Network Policy (Cô lập Network)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gpu-lab-network-policy
  namespace: gpu-lab
spec:
  podSelector:
    matchLabels:
      app: gpu-container
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Cho phép kết nối TCP vào port 8888 (JupyterLab)
    - ports:
        - protocol: TCP
          port: 8888
  egress:
    # 1. Cho phép phân giải tên miền (DNS)
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # 2. Cho phép ra ngoài Internet (HTTP/HTTPS) NHƯNG CHẶN mạng nội bộ (LAN/VPC)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8       # Chặn dải IP private hạng A
              - 172.16.0.0/12    # Chặn dải IP private hạng B (Docker/K8s mặc định)
              - 192.168.0.0/16   # Chặn dải IP private hạng C (Mạng nhà/văn phòng)
              - 169.254.0.0/16   # Chặn dải IP Cloud Metadata API (Chống cướp quyền Cloud)
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
