resources:
- role.yaml
- service_account.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- notebooklab_admin_role.yaml
- notebooklab_editor_role.yaml
- notebooklab_viewer_role.yaml
