apiVersion: lab.ngtukien.id.vn/v1alpha1
kind: VirtualNotebook
metadata:
  name: virtualnotebook-sample
  labels:
    UserID: "1"
    ProjectID: "1"
spec:
  # Số lượng bản sao (1 = Chạy, 0 = Tạm dừng)
  # replicas: 1 
  image: "jupyter/scipy-notebook:latest"
  
  # Cấu hình vòng đời
  lifecycle:
    idleTimeoutMinutes: 60
    maxLifespanHours: 12
    
  # Yêu cầu tài nguyên tính toán cơ bản
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
      
  # Cấu hình GPU (Có thể đổi enable thành false nếu chạy máy thường)
  gpu: 
    enable: false
    type: "hami"
    hami:
      cores: 20       
      memory: "16Gi" 

  # Cấu hình ổ cứng lưu trữ
  storage:
    workspace:
      size: "5Gi"
      # Hãy sửa lại cho đúng với StorageClass trên cụm của bạn, ví dụ: "local-path", "nfs-client"
      # storageClassName: "local-path" 
      mountPath: "/workspace"
