FROM ghcr.io/ngtukien/jupiter-operator/base-image:latest

# Install PyTorch (backend) and HuggingFace ecosystem
RUN pip3 install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

# Install HuggingFace ecosystem
RUN pip3 install --no-cache-dir \
    transformers datasets evaluate accelerate peft bitsandbytes sentencepiece trl