FROM nvcr.io/nvidia/cuda:12.4.1-base-ubuntu22.04

# KubeClass Base Image
ENV DEBIAN_FRONTEND=noninteractive

# Create candidate user and set a default password
RUN useradd -ms /bin/bash candidate && echo 'candidate:candidate' | chpasswd

# Install core utilities and Python
RUN apt-get update -o Acquire::Retries=3 && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    python3 python3-pip git \
    && rm -rf /var/lib/apt/lists/*

# Install lightweight generic ML tools and JupyterLab
RUN pip3 install --no-cache-dir --default-timeout=100 \
    numpy pandas scikit-learn matplotlib xgboost jupyterlab

# Set default shell to bash for Jupyter terminal
ENV SHELL=/bin/bash

# Copy the MOTD file and force bash to display it on exec
COPY motd /etc/motd
RUN echo "export PS1='\[\e[1;31m\]root\[\e[m\]@\[\e[1;36m\]gpu-lab\[\e[m\]:\[\e[1;33m\]\w\[\e[m\]\$ '" >> /home/candidate/.bashrc && \
    echo "echo -e '\e[1;36m'" >> /home/candidate/.bashrc && \
    echo "cat /etc/motd" >> /home/candidate/.bashrc && \
    echo "echo -e '\e[0m'" >> /home/candidate/.bashrc

# Giữ Container sống vô thời hạn để dùng lệnh `kubectl exec`
CMD ["sleep", "infinity"]
