ARG IMAGE_NAME=gpu-container
ARG IMAGE_TAG=tensorflow
FROM ghcr.io/nguyentukien/gpu-container:slim

# Install TensorFlow and related libraries
RUN pip3 install --no-cache-dir \
    tensorflow[and-cuda] keras tensorboard