ARG IMAGE_NAME=gpu-container
ARG IMAGE_TAG=pytorch
FROM ghcr.io/nguyentukien/gpu-container:slim

RUN pip3 install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124