ARG IMAGE_NAME=gpu-container
ARG IMAGE_TAG=huggingface
FROM ghcr.io/nguyentukien/gpu-container:slim

# Install PyTorch (backend) and HuggingFace ecosystem
RUN pip3 install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

RUN pip3 install --no-cache-dir \
    transformers datasets evaluate accelerate peft bitsandbytes sentencepiece trl