ARG IMAGE_NAME=jupiter-container
ARG IMAGE_TAG=tensorflow
FROM ghcr.io/ngtukien/jupiter-container:slim

# Install TensorFlow and related libraries
RUN pip3 install --no-cache-dir \
    tensorflow[and-cuda] keras tensorboard